In [1]:
import seaborn as sns

In [2]:
penguins = sns.load_dataset('penguins')

In [3]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [4]:
from sklearn.ensemble import RandomForestClassifier

Parameters for RFC are X and y.
X is the feature matrix (the input), y is the outcome (usually a column vector).
In this case, y could be the species column and X all of the other variable columns (except the species column!)

In [5]:
species = penguins.species
species

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: str

In [7]:
everything_else = penguins.drop(columns='species')

In [8]:
everything_else

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...
339,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Biscoe,49.9,16.1,213.0,5400.0,Male

In [9]:
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
OneHotEncoder().fit(everything_else)

OneHotEncoder()

Note: 'fit' here would be easier to explain if fitting numeric data to a distribution had already been discussed.

In [17]:
OHE = OneHotEncoder(sparse_output=False).fit_transform(everything_else)

in the Lab lesson, they filter out island and sex variables. we could do the same, to keep things simple. but want to bring them back later for discussion. or at least the island, since sex would be relatively easily encoded as well. Brings good opportunities to discuss some of the complexities that need to be considered in practice, with the help of your local statistician.

Next steps: follow the Lab DL lesson, i.e. use pandas to do the OHE. Consider removing only island at this stage and not sex as well.